# Site settings
#--------------
title: Colgate University
header-img: assets/img/home-bg.jpg
logo: assets/ico/logo.png
email: jagarwal@colgate.edu
copyright_name: Colgate University
description: The electronics enthusiasts of Colgate
meta-description: Website for The Colgate Technic Titans.
#twitter_username: SBootstrap
github_username:  Jaanhvi18
#facebook_username:  IronSummitMedia
#email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
syntaxtheme: friendly
paginate: 5
paginate_path: "blog/page:num"
exclude: ["scripts", "node_modules","README.md"]
gems: ['jekyll-paginate', 'jekyll-sass-converter']

# Configuration for url/path
baseurl: /electronics-club
# url: https://stab-iitb.org/electronics-club

# Permalink
permalink: /blog/:year/:month/:title/

# navbar menu
nav_menu:
    - name: Blog
      url: "/blog"
    - name: Tutorials
      url: "/tutorials"
    - name: Events
      url: "/events"
    - name: Chat
      url: "/chat"
    # - name: Team
    #   url: "/teampage"
# Declaring tutorials collection
collections:
  tutorials:
    permalink: /tutorials/:path/
    output: true
  events:
    permalink: /events/:path/
    output: true

# For comments sections
disqus:
    short_name: ctt
    comment_count: true
    developer_mode: true

category_dir: blog
